/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "Pausable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Pausable__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "PoolBet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PoolBet__factory>;
    getContractFactory(
      name: "BundlesBridge",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BundlesBridge__factory>;
    getContractFactory(
      name: "IBundlesToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBundlesToken__factory>;
    getContractFactory(
      name: "BundlesLock",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BundlesLock__factory>;
    getContractFactory(
      name: "BundlesToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BundlesToken__factory>;
    getContractFactory(
      name: "Prediction",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Prediction__factory>;
    getContractFactory(
      name: "BundlesTestToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BundlesTestToken__factory>;
    getContractFactory(
      name: "AccessProtected",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccessProtected__factory>;
    getContractFactory(
      name: "EIP712Base",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EIP712Base__factory>;
    getContractFactory(
      name: "NativeMetaTransaction",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.NativeMetaTransaction__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "Pausable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Pausable>;
    getContractAt(
      name: "ERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "PoolBet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.PoolBet>;
    getContractAt(
      name: "BundlesBridge",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BundlesBridge>;
    getContractAt(
      name: "IBundlesToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IBundlesToken>;
    getContractAt(
      name: "BundlesLock",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BundlesLock>;
    getContractAt(
      name: "BundlesToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BundlesToken>;
    getContractAt(
      name: "Prediction",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Prediction>;
    getContractAt(
      name: "BundlesTestToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BundlesTestToken>;
    getContractAt(
      name: "AccessProtected",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AccessProtected>;
    getContractAt(
      name: "EIP712Base",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.EIP712Base>;
    getContractAt(
      name: "NativeMetaTransaction",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.NativeMetaTransaction>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
